from .animal import Animal
from .crocodile import Crocodile
from .dolphin import Dolphin
from .donkey import Donkey
from .eel import Eel
from .gecko import Gecko
from .goldfish import Goldfish
from .lizard import Lizard
from .llama import Llama
from .monkey import Monkey
from .ostrich import Ostrich
from .shark import Shark
from .snake import Snake
from .tiger import Tiger
from .turtle import Turtle
from .whale import Whale
